/*========================================================
 * VGExceptions.h
 * @author Sergey Mikhtonyuk
 * @date 01 May 2009
=========================================================*/
#ifndef _VG_EXCEPTIONS_H__
#define _VG_EXCEPTIONS_H__

#include <exception>

namespace VG
{
	/// Base class for all exceptions generated in VG library
	/** @ingroup VG */
	class VGException : public std::exception
	{
	public:
		VGException() : std::exception() { }
		VGException(const char* msg) : std::exception(msg) { }
	};

	//////////////////////////////////////////////////////////////////////////

	/// Generated by processing units in case of data-command mismatch
	/** @ingroup VG */
	class VGFormatException : public VGException
	{
	public:
		VGFormatException() : VGException() { }
		VGFormatException(const char* msg) : VGException(msg) { }
	};

} // namespace

#endif	// _VG_EXCEPTIONS_H__